services:
  auth_service:
    url: http://auth-service:${AUTH_SERVICE_PORT}
  tenant_service:
    url: http://tenant-service:${TENANT_SERVICE_PORT}
  page_service:
    url: http://page-service:${PAGE_SERVICE_PORT}

rate_limiting:
  enabled: true
  requests_per_minute: 100

authentication:
  jwt_secret: ${JWT_SECRET}
