apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
    tier: backend
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api-gateway
  type: ClusterIP
