apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  namespace: default
  labels:
    app: tenant-service
    tier: backend
spec:
  selector:
    app: tenant-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: tenant-service
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-db-service
  labels:
    app: tenant-service-db
spec:
  ports:
    - port: 5432
  selector:
    app: tenant-service-db
